### PR TITLE
Rename sources from .f90 to .F90

### PR DESCRIPTION
**Pull request by szaghi**
Dear @victorsndvg 

I have merged your last fork and on the base of it I rename the sources from .f90 .F90 in order to automatically trigger the preprocessor when compiling them even without an explicit -cpp (thus we are more _standardized_ with other Fortraners).

My workflow remains the same of the older one (FoBiS build), but I think I have broken your Cmake-based workflow. Because I am not able to test it (I do not know how to use/config cmake) you should test/amend the cmake configuration if you want to merge this PR.

Thank you for your help.

### CODE REVIEW

**Comment by victorsndvg** [comment]
@szaghi , nice to hear you again! 

Now I know your preferences about fortran source files extensions and I will follow them when modifying  your projects. :smile: 

It seems that all is working as expected with the CMake compilation system for PENF.  I usually add a variable (`${PROJECT_NAME}_ENABLE_TESTS`) to optionally  compile/tests test sources. 

For example, the easy way to configure and compile PENF with CMake is:

``` sh
mkdir build
cd build
cmake $PATH_TO_PENF
```

If you also want to compile test sources and test them with CTest:

``` sh
mkdir build
cd build
cmake -DPENF_ENABLE_TESTS=ON $PATH_TO_PENF
ctest -T Test -T Coverage -T Memcheck
```

It's ok for you?

**Comment by szaghi** [comment]
It is wonderful, maybe I have to add doc on how to compile with cmake...

**Comment by victorsndvg** [comment]
Sorry I forgot to tell this: another CMake nice tool is `cmake-gui`. Is a GUI that allows you to configure your project and generate de compilation system (for example, `Makefiles`). 

With this GUI you can see all the "configurable" variables of your project in a more friendly user interface.
The way to use `cmake-gui` is really easy:

```
mkdir build
cd build
cmake -gui$PATH_TO_PENF
```

**Comment by szaghi** [comment]
@victorsndvg GUI for me... _vade retro satana_... my life is in a terminal :smile: 

Just kidding, thank you for pointing it out, maybe I will try it.

**Comment by victorsndvg** [comment]
I also prefer terminal. But is good starting point for end users and also for new developers to understand the variables involved in the compilation system in a single sight. very useful! (but only once per project :laughing: )

**Pull request merged**
